### ISSUE TITLE
can you release a new version?

### ISSUE THREAD

**Issue by DavidBadura** [gremo/CiconiaBundle#2]
for symfony 3.x :)

**Comment by DavidBadura** [comment]
or can i do that?

**Comment by gremo** [comment]
Hi David, AFAIK Ciconia still doesn't support Symfony 3. This bundle is fully compatible with Symfony 3... do you mean a new tag?

**Comment by DavidBadura** [comment]
it looks like Ciconia is no longer maintained. so we switched to https://github.com/thephpleague/commonmark

thank you for your great work!
